yggdrasil:
  application:
    namespace: "dev"
  client:
    github.com.codesjoy.yggdrasil.example.sample:
      remote:
        endpoints:
          - address: "127.0.0.1:55879"
            protocol: "grpc"
  interceptor:
    unary_client: "logger"
    stream_client: "logger"
    config:
      logger:
        print_req_and_res: true

  remote:
    logger_level: debug
